# Generated by Django 5.2.9 on 2026-01-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interioerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Pass/Contected')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='add_page',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
